### ISSUE TITLE
中文字符乱码的问题

### ISSUE THREAD

**Issue by lantian250** [jeessy2/backup-x#100]
如果备份脚本里有涉及中文字符，会有乱码的情况，导致无法执行成功
![image](https://github.com/jeessy2/backup-x/assets/40285666/9fbdb5d6-3b0b-453a-bdbd-e7fd982c6d90)
我在Client里的backup.go文件中，shellString写入前进行了GBK转码，就能正常执行
```
encoder := simplifiedchinese.GBK.NewEncoder()
shellString, err = encoder.String(shellString)
```
![image](https://github.com/jeessy2/backup-x/assets/40285666/c30fcf85-ce3c-4eaf-b754-42b5af7dac8e)
另外还有个问题，shell.CombinedOutput()这段代码，获取的内容，中文字符会变成x开头的字符
![image](https://github.com/jeessy2/backup-x/assets/40285666/74f2ab8c-6ebb-458b-aac2-5032ab6e2f50)

**Comment by jeessy2** [comment]
欢迎PR，需要注意兼容其他系统
