### ISSUE TITLE
mysqldump -h127.0.0.1 -uroot -p12A34B56C --all-databases 1>2024-01-13-08-44.sql 'mysqldump' 

### ISSUE THREAD

**Issue by aumcreeper** [jeessy2/backup-x#101]
![image](https://github.com/jeessy2/backup-x/assets/156485895/6bf85c17-2563-406f-935e-9f5dad35d0f8)
May I ask where the problem lies

**Comment by jeessy2** [comment]
can't find the mysqldump on windows, please Install the MySQL-Client
