### ISSUE TITLE
PGPASSWORD' 不是内部或外部命令，也不是可运行的程序或批处理文件

### ISSUE THREAD

**Issue by 2849799912** [jeessy2/backup-x#105]
PGPASSWORD="#{PWD}" pg_dump --host 127.0.0.1 --port 5432 --dbname name --user postgres --create --file #{DATE}.sql  这句会提示PGPASSWORD' 不是内部或外部命令，也不是可运行的程序或批处理文件

**Comment by jeessy2** [comment]
这个是docker中，其他环境根据实际情况写
