### ISSUE TITLE
ubuntu22.04 本地安装失败

### ISSUE THREAD

**Issue by Shimada666** [jeessy2/backup-x#113]
系统：ubuntu22.04

![83e5b199e51a3081494e912d4977b509](https://github.com/jeessy2/backup-x/assets/33391300/73214975-e839-4606-bab1-07821b9d6548)

提示安装成功，但是没有进程，通过 systemctl 查看服务状态，发现是 loaded
![e0dd56cce04c4f80f2ee6efb77488bc5](https://github.com/jeessy2/backup-x/assets/33391300/165e0315-ceb4-44a8-822a-0a072db5a2b6)

尝试启动报错

![7c694364f84c9b7275682644daf34211](https://github.com/jeessy2/backup-x/assets/33391300/846ff5fd-4526-4734-b65a-2644d5984e4e)

![7ba4df86344b093f6e55d4d685055496](https://github.com/jeessy2/backup-x/assets/33391300/296c3fd4-26d5-44da-bb87-e789c1747776)

前台启动正常
![c66dcf0ee24c8c40cb839f9351563b35](https://github.com/jeessy2/backup-x/assets/33391300/07f4829d-d9f2-4828-b826-845ca28470ad)

请问可以帮忙解决下吗

**Comment by jeessy2** [comment]
服务没起来？unit network.target not found
可以用docker

**Comment by Shimada666** [comment]
docker 是正常的，这次想试本地安装是因为有将不同路径下的数据备份到备份目录下的需求。如果无法解决我先用 docker 好了

**Comment by Shimada666** [comment]
我现在做法是把文件改了下丢到系统级的 systemd 下了，已经可以了

**Comment by Shimada666** [comment]
经过测试，用户的 systemd 文件也能用，只要注释这两行就行了
#Requires=network.target
#After=network-online.target

**Comment by jeessy2** [comment]
也可以移除main.go中的代码

**Comment by jeessy2** [comment]
可能是安装为了用户服务，准备不默认安装为用户服务

**Comment by jeessy2** [comment]
有空试下v2.7.3版本，不需要注释那两行

**Comment by Shimada666** [comment]
2.7.4 版本完美运行，运行一天无异常，非常感谢
