### ISSUE TITLE
安全漏洞

### ISSUE THREAD

**Issue by sky22333** [jeessy2/backup-x#117]
### 2：建议删除项目中的图标减少特征，同时将面板额外做一个登录页面，登录后才能看到核心功能，不要直接暴露这个面板是干什么的，同时加上人机验证，毕竟数据是无价的

---

![8120e058debdc126a632f40eee20a085](https://github.com/user-attachments/assets/42e9d07d-c417-409a-b929-07e1e48697af)

**Comment by jeessy2** [comment]
可以PR

**Comment by jeessy2** [comment]
这个本来就内网使用的

**Comment by jeessy2** [comment]
初始化必须设置账号密码的，只有这个安装后啥不管才看得见
