### ISSUE TITLE
feature:备份文件支持上传到oss？

### ISSUE THREAD

**Issue by CodingOX** [jeessy2/backup-x#16]
比如常见的对象存储
- 阿里云的OSS
- AWS的 Amazon S3
- 腾讯云 COS
- 七牛云 Kodo
- MinIO

**Comment by jeessy2** [comment]
支持的。我用的MinIO

**Comment by CodingOX** [comment]
> 支持的。我用的MinIO

实测，OSS支持，MinIO支持，其他的遵循S3协议的应该都支持的！
