### ISSUE TITLE
feature:关键信息加密

### ISSUE THREAD

**Issue by CodingOX** [jeessy2/backup-x#17]
已经在内网使用了一段时间，很稳定，点个👍🏻。不过用的过程发现了一些可以改进的地方。
1. 数据库备份的时候，`-p123456`这样的方式过于粗暴，不够安全【表面的安全都没有】，是否考虑支持用户自定的`{pwd}`这样的占位符占位，然后在下面添加变量的形式来支持，这个变量输入后可以是*号。
2. `AccessKey `和`SecretKey `，特别是后者，目前还是明文显示的，建议改为*号。
*背后还可以自定义或者默认一个加密key，通过启动的时候传入，页面*背后显示的都是加密后的字段，运行的时候，再解密一次更好。

**Comment by jeessy2** [comment]
好的提议，欢迎PR

**Comment by jeessy2** [comment]
v1.3.1已支持。aes-gcm256加密，当然通过那个key也可以解出来
