### ISSUE TITLE
QA:数据库备份外还支持哪些操作？

### ISSUE THREAD

**Issue by CodingOX** [jeessy2/backup-x#18]
`ReadeMe`中项目描述的是数据库的备份，文档也提到支持其他数据的备份，比如还有哪些？
我看容器里面没有`ssh`，那是否不支持跨主机的操作？比如我想备份`A`主机的`/config`目录，是否支持？

**Comment by jeessy2** [comment]
只要有输出的文件，都可以支持。
理论上是可以的。就是这个`shell`需要好好设计一下

**Comment by jeessy2** [comment]
v2.0.0支持备份文件到对象存储了，对像存储之间备份...
