### ISSUE TITLE
卸载时提示服务未安装

### ISSUE THREAD

**Issue by dreyooneday** [jeessy2/backup-x#22]
2022/01/18 12:11:10 backup-x 服务未安装

**Comment by jeessy2** [comment]
什么操作系统？刚试了，正常卸载

**Comment by dreyooneday** [comment]
armbian，现在没事了，已手动删除>.<

**Comment by jeessy2** [comment]
试下2.1.2版本。以前是安装为用户服务，2.1.2后默认安装为系统服务
