### ISSUE TITLE
安装提示错误ERR: exit status 1 （未使用docker，centos7.6）

### ISSUE THREAD

**Issue by kksay2010** [jeessy2/backup-x#23]
./backup-x -s install
2022/02/17 05:45:03 安装 backup-x 服务失败, ERR: exit status 1
2022/02/17 05:45:03 请确保使用如下命令: ./backup-x -s install

**Comment by jeessy2** [comment]
前面加sudo试下

**Comment by jeessy2** [comment]
试下2.1.2版本。以前是安装为用户服务，2.1.2后默认安装为系统服务
