### ISSUE TITLE
建议增加SCP传输文件功能 及 任务管理界面

### ISSUE THREAD

**Issue by kksay2010** [jeessy2/backup-x#25]
1、两台服务器免密传输设置后（这样就能避免web端输入服务器密码了），可以使用scp功能发送备份文件。脚本示例如下：
      scp -r $datepath root@172.16.27.107:/data/pgdb_backup/databack

     功能放到备份配置里面。

2、任务管理界面我是截图其他软件，做个类似查看页面就行，方便运维巡检备份任务情况

**Comment by kksay2010** [comment]
脚本示例全面的如下：

cd /data/pgdb_backup; 
datepath=$(date +%Y%m%d); 
mkdir $datepath; 
cd $datepath; 
PGPASSWORD="【数据库密码】" /data/soft/pgsql/bin/pg_dumpall -h 127.0.0.1 -p 5432 -U postgres -c -f pg_data.bak;
scp -r $datepath  root@172.16.27.107:/data/pgdb_backup/databack;
## 172.16.27.107 是汇总服务器

**Comment by jeessy2** [comment]
二次备份建议放到对象存储中，使用命令权限太大

**Comment by jeessy2** [comment]
巡检使用webhook通知。每天看下消息就OK。系统化的页面不太适合这个小小的备份工具
