### ISSUE TITLE
执行的时候报错

### ISSUE THREAD

**Issue by TankTim68** [jeessy2/backup-x#34]
2022/08/06 07:10:31 执行shell的输出为空
2022/08/06 07:10:31 项目 DB_backup 没有输出包含 2022-08-06_07_10 的文件名

![11](https://user-images.githubusercontent.com/100554494/183252759-3cb911a8-6ca1-41bd-8d72-9265d0d8fb18.png)

**Comment by jeessy2** [comment]
输出目录不对，不能是其他目录。参考说明，不然找不到文件

**Comment by TankTim68** [comment]
但是对应的目录其实是有生成成功的。只是shell那边是报错的。好的，感谢老大回复。谢谢。

**Comment by TankTim68** [comment]
再请教一下，备份周期是不是只能24小时内？

**Comment by jeessy2** [comment]
不限制24小时内
