### ISSUE TITLE
怎么获取Endpoint 这个参数呢？

### ISSUE THREAD

**Issue by pengfenhua** [jeessy2/backup-x#36]
怎么获取Endpoint 这个参数呢？

**Comment by jeessy2** [comment]
对象存储的endpoint，就一个URL。网上去了解一下

**Comment by pengfenhua** [comment]
> 

2022/08/07 14:33:19 执行备份shell失败: time='2022-08-07T14:33:19+08:00' level=info msg='Starting sync' time='2022-08-07T14:33:19+08:00' level=error msg='Sync error: pipeline step: 0 (ListSource) failed with error: stat /data: no such file or directory, terminating' time='2022-08-07T14:33:19+08:00' level=info msg='Pipeline step finished' ErrorObj=1 InputObj=0 InputObjSpeed=0 OutputObj=0 OutputObjSpeed=0 stepName=ListSource stepNum=0 time='2022-08-07T14:33:19+08:00' level=info msg='Pipeline step finished' ErrorObj=0 InputObj=0 InputObjSpeed=0 OutputObj=0 OutputObjSpeed=0 stepName=FilterObjectsExistNot stepNum=1 time='2022-08-07T14:33:19+08:00' level=info msg='Pipeline step finished' ErrorObj=0 InputObj=0 InputObjSpeed=0 OutputObj=0 OutputObjSpeed=0 stepName=LoadObjData stepNum=2 time='2022-08-07T14:33:19+08:00' level=info msg='Pipeline step finished' ErrorObj=0 InputObj=0 InputObjSpeed=0 OutputObj=0 OutputObjSpeed=0 stepName=UploadObj stepNum=3 time='2022-08-07T14:33:19+08:00' level=info msg='Pipeline step finished' ErrorObj=0 InputObj=0 InputObjSpeed=0 OutputObj=0 OutputObjSpeed=0 stepName=Terminator stepNum=4 time='2022-08-07T14:33:19+08:00' level=info msg='Duration: 9.868809ms' durationSec=0.009865272 time='2022-08-07T14:33:19+08:00' level=error msg='Sync Failed' status=1


这个错误是什么原因呢？

**Comment by jeessy2** [comment]
没这个目录。 stat /data: no such file or directory, terminating
