### ISSUE TITLE
日志报错。有空的话求解答一下。感谢

### ISSUE THREAD

**Issue by pengfenhua** [jeessy2/backup-x#37]
2022/08/07 14:39:38 创建bucket: bitwarden 失败, ERR: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'cn-north-1' is wrong; expecting 'us-west-1' status code: 400, request id: YM99XBP7RK09C90Y, host id: +h+BAP06aNfoeFZu+g8lmPLj0DjTtTaDUJw+VReegiyjUF95EyPoaXbARFqBAVm99+kmlhJk+Mc=
2022/08/07 14:39:38 正在备份项目: bitwarden_backup ...
2022/08/07 14:39:38 bitwarden_backup项目将在10.3小时后运行
2022/08/07 14:39:38 bitwarden_backup 执行shell的输出: 鼠标移动此处查看
2022/08/07 14:39:38 执行备份shell失败: time='2022-08-07T14:39:38+08:00' level=info msg='Starting sync' time='2022-08-07T14:39:38+08:00' level=error msg='Sync error: pipeline step: 0 (ListSource) failed with error: stat /root/bitwarden/data/db.sqlite3: no such file or directory, terminating' time='2022-08-07T14:39:38+08:00' level=info msg='Pipeline step finished' ErrorObj=1 InputObj=0 InputObjSpeed=0 OutputObj=0 OutputObjSpeed=0 stepName=ListSource stepNum=0 time='2022-08-07T14:39:38+08:00' level=info msg='Pipeline step finished' ErrorObj=0 InputObj=0 InputObjSpeed=0 OutputObj=0 OutputObjSpeed=0 stepName=FilterObjectsExistNot stepNum=1 time='2022-08-07T14:39:38+08:00' level=info msg='Pipeline step finished' ErrorObj=0 InputObj=0 InputObjSpeed=0 OutputObj=0 OutputObjSpeed=0 stepName=LoadObjData stepNum=2 time='2022-08-07T14:39:38+08:00' level=info msg='Pipeline step finished' ErrorObj=0 InputObj=0 InputObjSpeed=0 OutputObj=0 OutputObjSpeed=0 stepName=UploadObj stepNum=3 time='2022-08-07T14:39:38+08:00' level=info msg='Pipeline step finished' ErrorObj=0 InputObj=0 InputObjSpeed=0 OutputObj=0 OutputObjSpeed=0 stepName=Terminator stepNum=4 time='2022-08-07T14:39:38+08:00' level=info msg='Duration: 4.687948ms' durationSec=0.004685223 time='2022-08-07T14:39:38+08:00' level=error msg='Sync Failed' status=1

**Comment by jeessy2** [comment]
看下你配置

**Comment by pengfenhua** [comment]
> 看下你配置

![image](https://user-images.githubusercontent.com/59499062/183279036-76b246e6-9e49-4847-9e02-f2a1eedf782b.png)


![image](https://user-images.githubusercontent.com/59499062/183279051-ce110b95-05ed-4a3d-851b-47e095341f13.png)

**Comment by jeessy2** [comment]
/root/bitwarden/data/db.sqlite3这个地址存在？

**Comment by jeessy2** [comment]
你用的aws的对象存储? 需要程序升级到2.1.1 region没实现。默认使用cn-north-1
endpoint前面需要加https://s3.us-west-1.amazonaws.com
