### ISSUE TITLE
windows环境下，生成了.bat脚本，但是不会自己执行

### ISSUE THREAD

**Issue by neroti9n** [jeessy2/backup-x#39]
如题，.bat脚本双击能正确执行

安装包：backup-x_2.1.1_Windows_x86_64.tar.gz
操作：pg_dump备份数据库

**Comment by jeessy2** [comment]
什么bat脚本，Windows可以安装服务运行
页面看到没有，有输出的日志么

**Comment by neroti9n** [comment]
![image](https://user-images.githubusercontent.com/15121488/184576116-a4ac209d-2dbc-46d6-9c28-6561efe824fd.png)
![image](https://user-images.githubusercontent.com/15121488/184576235-4873b948-2323-45a1-bb50-28d13a5cd3bc.png)
日志就一直卡在正在备份，看到目录当中生成了一个.bat脚本，但是备份文件没有出来

**Comment by jeessy2** [comment]
把bat里面的拷出来在cmd下面运行，看是不是卡起的。
也有可能备份太大，需要等待

**Comment by neroti9n** [comment]
拷贝出来是能运行的，直接执行也行，pg_dump执行会立马在指定目录创建一个文件，通过应用，这个文件没有生成

**Comment by jeessy2** [comment]
数据库也不大吗?
`--file #{DATE}.sql` 使用相对路径就可以了。路径不需要指定全路径

**Comment by neroti9n** [comment]
相对路径也不会自动运行

**Comment by neroti9n** [comment]
![image](https://user-images.githubusercontent.com/15121488/184586713-ba66a4ab-0fd8-4a21-9695-12ac76406458.png)

**Comment by neroti9n** [comment]
![image](https://user-images.githubusercontent.com/15121488/184586750-cb96cc53-a3db-4218-be26-63e8f1fc3af5.png)
还有这个备份周期改了不生效

**Comment by jeessy2** [comment]
要等待到起始时间执行一次，后面才会按照周期来执行

**Comment by jeessy2** [comment]
还是把命令考出来能生成一个备份文件否，备份命令参考首页说明来。在发来看下，重要信息用`xx`替代

**Comment by neroti9n** [comment]
![image](https://user-images.githubusercontent.com/15121488/184592982-6a7d6ba1-10ad-4e32-9295-0f8a0c31c145.png)
考出来能生成一个备份文件，如上图

**Comment by jeessy2** [comment]
执行那个shell要输入密码，所以一直卡到哪里。
windows应该这么用：
```
SET PGPASSWORD=#{PWD}
pg_dump --host 192.168.1.11 --port 5432 --dbname db-name -Upostgres --clean --create --file #{DATE}.sql
```

**Comment by neroti9n** [comment]
谢谢，可以了
我一开始有试过这样的写法，可能哪里没弄对，然后我还特地找了pg不用输密码的方式，你看我在上面cmd当中没有提示要输密码，我以为不是输入密码的问题了

**Comment by neroti9n** [comment]
再想请问下，如果单纯想同步文件夹，windows下应该怎么写
我填了对象存储配置，在数据库备份文件好后，成功的同步到了s3，想试下怎么可以同步指定文件夹

**Comment by jeessy2** [comment]
首页有说明参考配置一下。
s3sync,rclone都可以

**Comment by neroti9n** [comment]
s3sync --fs-disable-xattr --filter-not-exist --tk #{AccessKey} --ts #{SecretKey} --te #{Endpoint} **fs://F://ti9nBackup/** s3://#{BucketName}/test/
加粗本地路径这块不知道该如何填写

**Comment by jeessy2** [comment]
s3sync好像不支持windows
用rclone

**Comment by neroti9n** [comment]
数据库备份文件是如何同步上去的，cmd里提示没有s3sync和rclone这两个命令

**Comment by jeessy2** [comment]
电脑要安装才有，backup-x就一个自动运行脚本的程序，提供增强功能

**Comment by neroti9n** [comment]
数据库备份文件同步到s3不是用的s3sync和rclone？

**Comment by jeessy2** [comment]
不是。那个是自己写的

**Comment by neroti9n** [comment]
好吧，有定时备份已经方便不少了👍
