### ISSUE TITLE
postgresql 备份 不支持14.1吗

### ISSUE THREAD

**Issue by ssj111** [jeessy2/backup-x#43]
2022/08/24 16:15:20 执行备份shell失败: pg_dump: error: server version: 14.1 (Debian 14.1-1.pgdg110+1); pg_dump version: 13.7 (Debian 13.7-0+deb11u1) pg_dump: error: aborting because of server version mismatch

**Comment by jeessy2** [comment]
Debian的client还是13的。
使用系统安装比较合适

**Comment by kksay2010** [comment]
> Debian的client还是13的。 使用系统安装比较合适

非常希望把 pg_dump version版本提升，我们计划采用pgsql14版本

**Comment by jeessy2** [comment]
> > Debian的client还是13的。 使用系统安装比较合适
> 
> 
> 
> 非常希望把 pg_dump version版本提升，我们计划采用pgsql14版本

可以。后面看docker中能安装不？看了文档应该可以
