### ISSUE TITLE
在windows下，安装服务后。执行备份操作。提示“执行shell的输出为空”

### ISSUE THREAD

**Issue by sjzxj** [jeessy2/backup-x#44]
2022/09/05 16:24:26 question_system项目将在0.6小时后运行
2022/09/05 16:24:26 正在备份项目: question_system ...
2022/09/05 16:24:26 执行shell的输出为空
2022/09/05 16:24:26 执行备份shell失败:

**Comment by sjzxj** [comment]
这是备份脚本：mysqldump -h127.0.0.1 -uroot -p123qwe question_system > question_system#{DATE}.sql

**Comment by jeessy2** [comment]
docker中运行？

**Comment by sjzxj** [comment]
windows 10 E盘一个目录。不是在docker中运行。

**Comment by jeessy2** [comment]
直接在cmd下面能运行不

**Comment by sjzxj** [comment]
第一次放到桌面直接打开exe文件，运行5天。没有问题。可以用。后来我说试试安装服务。就不行了。

**Comment by sjzxj** [comment]
安装服务是用管理员身份打开CMD安装成功，能登录和设置备份。就是保存运行时，出现错误提示：
2022/09/05 16:24:26 question_system项目将在0.6小时后运行
2022/09/05 16:24:26 正在备份项目: question_system ...
2022/09/05 16:24:26 执行shell的输出为空         ** （经过观察发现没有在备份目录生成shell脚本，导致无法执行shell命令）**
2022/09/05 16:24:26 执行备份shell失败:

**Comment by sjzxj** [comment]
安装服务是用管理员身份打开CMD安装成功，能登录和设置备份。就是保存运行时，出现错误提示：
2022/09/05 16:24:26 question_system项目将在0.6小时后运行
2022/09/05 16:24:26 正在备份项目: question_system ...
2022/09/05 16:24:26 执行shell的输出为空         ** （经过观察发现没有在备份目录生成shell脚本，导致无法执行shell命令）**
2022/09/05 16:24:26 执行备份shell失败:

**Comment by jeessy2** [comment]
当前用的什么版本？

**Comment by sjzxj** [comment]
2.1.2（最新的）

**Comment by jeessy2** [comment]
我这里输出不为空，能运行

**Comment by sjzxj** [comment]
对了。这个运行会生成缓存文件吗？我删除了试试。

**Comment by jeessy2** [comment]
没有缓存文件，有个临时shell文件

**Comment by sjzxj** [comment]
2022/09/05 21:09:03 question_system项目将在0.8小时后运行
2022/09/05 21:09:03 question_system 执行shell的输出: 鼠标移动此处查看
2022/09/05 21:09:03 执行备份shell失败: E:\backup-x\backup-x-files\question_system>mysqldump -h127.0.0.1 -uroot -p123qwe question_system 1>question_system-2022-09-05_21_09.sql 'mysqldump' �����ڲ����ⲿ���Ҳ���ǿ����еĳ��� ���������ļ���

**Comment by sjzxj** [comment]
这个错误怎么看原因。

**Comment by jeessy2** [comment]
考出来执行，就看得到原因了。根据原因来修改

**Comment by sjzxj** [comment]
不好意思，不知道怎么考出来。但是我把服务卸载了。直接运行backup-x.exe之后在进行备份可以备份成功。在我重新安装服务后，还是这个错误。

**Comment by sjzxj** [comment]
E:\>mysqldump -h127.0.0.1 -uroot -p123qwe question_system >question_system-1222.sql
mysqldump: [Warning] Using a password on the command line interface can be insecure.

这个命令单独在cmd运行，可以生成备份文件。就是有个警告。

**Comment by jeessy2** [comment]
mysqldump -h127.0.0.1 -uroot -p123qwe question_system 1>question_system-2022-09-05_21_09.sql 就是这个命令

**Comment by sjzxj** [comment]
可以备份的。

**Comment by sjzxj** [comment]
单独运行。命令可以生成备份。
卸载服务后，在运行exe文件，也可以备份。
重新安装服务号，再备份，还是同样问题。不过会生成一个0k的sql文件。

**Comment by jeessy2** [comment]
windows应该这么用
```
SET MYSQL_PWD=#{PWD}
mysqldump -h127.0.0.1 -uroot test --file #{DATE}.sql
```

**Comment by jeessy2** [comment]
试了下。无用，放在外面可以，程序执行shell没有效果

**Comment by jeessy2** [comment]
gbk转utf8后，发现是这个问题：
要指定mysqldump路径
```
SET MYSQL_PWD=#{PWD}
"C:\\Program Files\\MySQL\\MySQL Server 5.7\\bin\\mysqldump" -hlocalhost -uroot test > #{DATE}.sql
```

**Comment by jeessy2** [comment]
试下2.1.3版本就可以看到错误

**Comment by sjzxj** [comment]
好的，谢谢。

**Comment by sjzxj** [comment]
可以了。

**Comment by sjzxj** [comment]
麻烦问下。这个的删除逻辑是按照文件名时间删除，还是按照文件最后一次创建或修改时间删除的。

**Comment by jeessy2** [comment]
> 麻烦问下。这个的删除逻辑是按照文件名时间删除，还是按照文件最后一次创建或修改时间删除的。

文件名的日期
