### ISSUE TITLE
mysql 使用docker 运行的 如何使用该系统备份，端口是4306

### ISSUE THREAD

**Issue by yanpengfei-git** [jeessy2/backup-x#47]
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/37141737/190943130-af8438b5-52f7-466c-b679-781f6be180d4.png">

提示mysqldump命令不存在

**Comment by jeessy2** [comment]
要在docker中运行backup-x才自动带mysql dump
系统中运行要手动安装mysql client

**Comment by yanpengfei-git** [comment]
> 要在docker中运行backup-x才自动带mysql dump
> 系统中运行要手动安装mysql client

系统中运行手动安装mysql client后，需要装MySQL服务吗，不太想在本机装数据库服务

**Comment by jeessy2** [comment]
那你在docker中运行backup-x
