### ISSUE TITLE
最多只能备份16个数据库么

### ISSUE THREAD

**Issue by happyseraph** [jeessy2/backup-x#49]
最多只能备份16个数据库么

**Comment by jeessy2** [comment]
只是页面上限制16个，实际上无限都可以的，不够可以PR。

**Comment by happyseraph** [comment]
该怎么加呢。。

**Comment by jeessy2** [comment]
要改代码，你需求要多少

**Comment by happyseraph** [comment]
另外加10个。。。

**Comment by jeessy2** [comment]
项目这么多？直接加配置文件里也是可以的

**Comment by jeessy2** [comment]
直接加配置文件。多出来的配置也会在页面显示

**Comment by jeessy2** [comment]
备份目录下有一个配置文件`.backup_x_config.yaml`
backupconfig下增加. 
```
- projectname: "test"
  command: ""
  savedays: 30
  savedayss3: 0
  starttime: 1
  period: 1440
  pwd: ""
  backuptype: 0
  enabled: 0
```

**Comment by happyseraph** [comment]
非常感谢！！！






16892425
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeessy2/backup-x"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月30日(星期三) 下午5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeessy2/backup-x] 最多只能备份16个数据库么 (Issue #49)





 
备份目录下有一个配置文件.backup_x_config.yaml
 backupconfig下增加.
 - projectname: "test"   command: ""   savedays: 30   savedayss3: 0   starttime: 1   period: 1440   pwd: ""   backuptype: 0   enabled: 0
