### ISSUE TITLE
为啥会出现这个错误

### ISSUE THREAD

**Issue by lucktoo** [jeessy2/backup-x#59]
C:\Users\xx\Downloads\backup-x_2.1.6_Windows_x86_64\backup-x-files\imap>mysqldump -h127.0.0.1 -uroot -paegtImapfenX --all-databases 1>2023-03-16_23_21.sql 'mysqldump' 不是内部或外部命令，也不是可运行的程序 或批处理文件。
我在docker 部署了一个应用
这个路径该怎么样的？
小白请教

**Comment by lucktoo** [comment]
大佬 没明白
是我需要在安装 mysql-client 就行了是吗

**Comment by lucktoo** [comment]
大佬 window 已经下载 mysql-client zip  也解压了  是怎么处理呢？

**Comment by lucktoo** [comment]
已安装了 ，为啥还是 C:\Users\xx\Downloads\backup-x_2.1.6_Windows_x86_64\backup-x-files\imap>mysqldump -h127.0.0.1 -uroot -paegtImapfenX --all-databases 1>2023-03-16_23_21.sql 'mysqldump' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

**Comment by lucktoo** [comment]
C:\Users\xx>mysqldump
'mysqldump' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by jeessy2** [comment]
那你没安装好。下个mysql exe文件安装

**Comment by lucktoo** [comment]
023/03/16 23:49:50 正在备份项目: imap ...
2023/03/16 23:49:50 imap项目将在23.2小时后运行
2023/03/16 23:49:51 imap 执行shell的输出: 鼠标移动此处查看
2023/03/16 23:49:51 执行备份shell失败: C:\Users\xx\Downloads\backup-x_2.1.6_Windows_x86_64\backup-x-files\imap>C:\mysql\bin\mysqldump -h127.0.0.1 -uroot -ptestImapfanX --all-databases 1>2023-03-16_23_49.sql mysqldump: [Warning] Using a password on the command line interface can be insecure. mysqldump: Couldn't execute 'SELECT COLUMN_NAME, JSON_EXTRACT(HISTOGRAM, '$.'number-of-buckets-specified'') FROM information_schema.COLUMN_STATISTICS WHERE SCHEMA_NAME = 'mysql' AND TABLE_NAME = 'columns_priv';': Unknown table 'column_statistics' in information_schema (1109)

**Comment by jeessy2** [comment]
网上自己搜索就知道怎么解决了

This is due to a new flag that is enabled by default in mysqldump 8. You can disable it by adding --column-statistics=0. The command will be something like:


mysqldump --column-statistics=0

**Comment by lucktoo** [comment]
多谢

**Comment by lucktoo** [comment]
多谢大佬  解决了 
C:\mysql\bin\mysqldump --column-statistics=0 -h127.0.0.1 -uroot -p#{PWD} --all-databases > #{DATE}.sql

--column-statistics=0   这个需要加上 因为 mysqldump 8  中默认启用了 一个新的标准 column-statistics，通过mysqldump --column-statistics=0 禁用
