### ISSUE TITLE
很nice的同步工具

### ISSUE THREAD

**Issue by langren1353** [jeessy2/backup-x#60]
感谢作者一直在更新，一直在迭代
我这边提一个小的问题，docker的环境中没有rclone，这个是不是后续会有嵌入进去的想法呢

**Comment by jeessy2** [comment]
可以考虑。rclone不是要单独运行配置吗？在docker中怎么配置

**Comment by langren1353** [comment]
可以考虑dockerfile中增加rclone的二进制包，然后给一个rclone的配置页面，或者不给页面也行
然后页面上增加一个启用rclone按钮就行了

**Comment by jeessy2** [comment]
启用是什么意思？没看明白
感觉在rclone在docker中不好使用，你能说下docker中如何使用不

**Comment by langren1353** [comment]
> 启用是什么意思？没看明白 感觉在rclone在docker中不好使用，你能说下docker中如何使用不

rclone安装的话，可以这么搞：curl https://rclone.org/install.sh | sudo bash
然后web页面上提供一个启动rclone的选项（复选框【是否启动rclone】+input框【rclone启动命令：hint：rclone copy xxx】）
然后用户勾选了的话，并且触发定时就会执行目标命令，这样就能很好的和rclone配合了

**Comment by jeessy2** [comment]
不是有输入命令的输入框了，为啥要单独弄一个，没看明白需求了

**Comment by jeessy2** [comment]
> > 不是有输入命令的输入框了，为啥要单独弄一个，没看明白需求了
> 
> 哦哦，我搞错了，主要问题还是docker镜像中没有带rclone，嘻嘻 不过感觉好像还是用户自己打一个新的镜像更合适一些

可安装为服务，直接调系统的rclone，这样更方便点
