### ISSUE TITLE
能不能直接支持备份到阿里云OSS和腾讯云COS

### ISSUE THREAD

**Issue by kksay2010** [jeessy2/backup-x#61]
能不能直接支持备份到阿里云OSS和腾讯云COS

**Comment by jeessy2** [comment]
可以的。对象存储填写相关信息

**Comment by kksay2010** [comment]
> 可以的。对象存储填写相关信息

使用这个命可以备份到阿里OSS和腾讯云COS吗

![11111](https://user-images.githubusercontent.com/29589474/230583316-a9adad60-917e-4894-8133-8150a1dedadc.png)

**Comment by jeessy2** [comment]
可以
