### ISSUE TITLE
请问BOSS： docker 安装完成，启动backup-x后进入Basic Authentication 的界面，我找到在backup-x-files下的.backup_x_config.yaml 的用户名和密码，仍然无法登录。

### ISSUE THREAD

**Issue by ApemanofBJ** [jeessy2/backup-x#64]

**Comment by jeessy2** [comment]
密码是加密后的，手工删除配置中的用户/密码，重启试下

**Comment by ApemanofBJ** [comment]
感谢！确实是这个问题，清空密码后即可。
又遇到一个脚本问题，请教：
执行备份shell失败: Enter password: mysqldump: Got error: 2002: 'Can't connect to MySQL server on '127.0.0.1' (115)' when trying to connect

docker 容器运行了一个mysql 容器：mysqldump -h 127.0.0.1  -uroot -p 123456  #{PWD}  schema_name > #{DATE}.sql

**Comment by jeessy2** [comment]
不能用127.0.0.1。用内网IP

**Comment by ApemanofBJ** [comment]
确实，在/etc/hosts 下 输入docker 内网IP ，可以直接解析了。
