### ISSUE TITLE
使用建议：保存（天）数是否可以改为保存最后几份（数量）？以及备份错误的再次执行？

### ISSUE THREAD

**Issue by babutree** [jeessy2/backup-x#65]
感谢开发者，这是一个非常棒的软件！
不过恰巧最近服务器出了故障，所以在使用中我有两个疑问：
1. 如果我设置保存（天）为30
恰好这30天我的数据库无法链接
第31天，之前的备份是不是依然保存？
如果不保存，那将是灾难！（比如我备份HomeAssistant的数据库，但是我又比较懒：）不会每天都去检查HomeAssistant是否有提示数据库失联，但其实HomeAssistant也会正常运行，通过Homekit看不到数据库是否错误）
为了规避我只能选择将保存天数设置更大，但是显然我的硬盘/对象存储可能会满，导致最新的又无法备份

2. 当数据库无法链接时，备份文件为0字节，显然这样的备份是无效的，但是系统好像没有判断依然生成了这个文件，可以看出2点整备份的文件是0字节，这样不管是保存天数还是保存数量，都无法解决因数据崩溃而导致的没有备份的问题。

# ls -lha
total 412M
drwxr-x--- 1 root root  200 Jun  3 17:31 .
drwxr-xr-x 1 root root   86 Jun  2 10:15 ..
-rw-r--r-- 1 root root    0 Jun  2 10:15 2023-06-02_10_15.sql
-rw-r--r-- 1 root root 205M Jun  2 10:27 2023-06-02_10_27.sql
-rw-r--r-- 1 root root    0 Jun  3 02:00 2023-06-03_02_00.sql
-rw-r--r-- 1 root root 207M Jun  3 17:31 2023-06-03_17_31.sql

所以这里是否可以更改为数量，而不是天数？再加上判断备份文件大小的逻辑？如果备份文件为0，多久后再重试？
谢谢！

**Comment by jeessy2** [comment]
可以设置一下Webhook通知的，里面有文件大小

保存天数或数量都会有这种问题，还是用保存天数？只要判断文件大小大于0的

**Comment by babutree** [comment]
感谢解答
问题的重点可能是备份出来的空文件，
如果不产生0字节文件
那版本就可以通过Syncthing的版本控制来解决
这个issue就先关了
