### ISSUE TITLE
能备份clickhouse吗

### ISSUE THREAD

**Issue by heziwenWork** [jeessy2/backup-x#74]

**Comment by jeessy2** [comment]
应该是可以的，这个需要你自己写脚本，backup-x只是一个定时执行你脚本的工具

**Comment by Shimada666** [comment]
我给个备份示例，配合 clickhouse-backup 一起使用。需要先配好 clickhouse-backup

clickhouse-backup create #{DATE} && zip -r #{DATE}.zip /var/lib/clickhouse/backup/#{DATE} && clickhouse-backup delete local #{DATE}
