### ISSUE TITLE
请问可以新增一个备份到Webdav的功能吗

### ISSUE THREAD

**Issue by Akimio521** [jeessy2/backup-x#90]
如题，最好备份文件夹的时候可以设置成增量备份

**Comment by jeessy2** [comment]
只支持备份至对象存储，WebDAV不支持，估计以后也不会直接支持。可以利用alist挂载对象存储间接支持

**Comment by Akimio521** [comment]
我的想法是让网盘作为灾备，但是alist好像不能提供对方存储的服务，只能把对象存储挂载到alist

**Comment by jeessy2** [comment]
对。那也可以把网盘挂载为WebDAV, 备份的时候直接就备份到挂载的目录

**Comment by jeessy2** [comment]
二次备份只支持对象存储

**Comment by Akimio521** [comment]
> 对。那也可以把网盘挂载为WebDAV, 备份的时候直接就备份到挂载的目录

意思是先把webdav挂载到nas的文件目录，再把文件目录传入docker？目前我的系统不太方便把webdav挂载到本地

**Comment by jeessy2** [comment]
差不多那意思。也可以找台其它电脑，安装minio，二次备份到对象存储

**Comment by Akimio521** [comment]
嗯，还是不太方便的，所以还是希望可以增加一个直接对接webdav的功能

**Comment by jeessy2** [comment]
估计以后也不支持WebDAV，只支持对象存储。考虑变通的方式或者自行弄个版本。。

**Comment by langren1353** [comment]
我记得我提交了的代码里面有rclone的依赖，所以你可以通过映射rclone的配置文件，然后去配置webdav用
